# Generated by Django 5.1.7 on 2025-03-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionEngine', '0003_auction_bid_auction_auctionengi_is_acti_43c02c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
