# Generated by Django 5.1.7 on 2025-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionEngine', '0004_alter_auction_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(null=True, upload_to='auctions/'),
        ),
    ]
