# Generated by Django 5.1.7 on 2025-03-26 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionEngine', '0007_alter_auction_end_time_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 15, 12, 1, 352342, tzinfo=datetime.timezone.utc)),
        ),
    ]
