# Generated by Django 5.1.7 on 2025-03-26 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionEngine', '0009_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 15, 26, 38, 711385, tzinfo=datetime.timezone.utc)),
        ),
    ]
