# Generated by Django 5.1.7 on 2025-03-28 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionEngine', '0010_alter_user_managers_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 14, 44, 51, 401082, tzinfo=datetime.timezone.utc)),
        ),
    ]
